version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule: 
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"